import type { News } from "@/lib/validations"

export const mockNewsData: News[] = [
    {
        id: "mock-politica-1",
        title: "Reunión del Consejo Municipal - Nuevas Ordenanzas",
        subtitle: "El consejo municipal se reunió para discutir nuevas ordenanzas locales",
        description: "Descripción detallada sobre las nuevas ordenanzas municipales que afectarán a la comunidad",
        mainCategory: "Politica",
        subCategory: "municipal",
        tags: ["consejo", "ordenanzas", "municipal"],
        author: "Redacción",
        date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
        image: "/placeholder.svg?height=400&width=600",
        imageUrl: "/placeholder.svg?height=400&width=600",
        imageCaption: "Reunión del Consejo Municipal",
        featured: true,
        breaking: false,
        views: 245,
        likes: 12,
        comments: 8,
        status: "published",
        slug: "reunion-consejo-municipal-nuevas-ordenanzas",
        excerpt: "El consejo municipal aprobó nuevas ordenanzas que entrarán en vigencia el próximo mes.",
        readTime: 3,
        source: "Municipalidad",
        location: "Centro Cívico",
        priority: 2,
        content: "Contenido completo sobre las nuevas ordenanzas municipales y su impacto en la comunidad.",
        summary: "Nuevas ordenanzas municipales aprobadas",
        youtubeLink: "",
    },
    {
        id: "mock-deporte-1",
        title: "Victoria Local en el Torneo Regional",
        subtitle: "El equipo local se impuso por 2-1 en un partido emocionante",
        description: "Crónica del partido que mantuvo a todos en vilo hasta el último minuto",
        mainCategory: "Deportes",
        subCategory: "futbol",
        tags: ["futbol", "torneo", "victoria", "local"],
        author: "Deportes",
        date: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
        image: "/placeholder.svg?height=400&width=600",
        imageUrl: "/placeholder.svg?height=400&width=600",
        imageCaption: "Celebración del gol de la victoria",
        featured: true,
        breaking: false,
        views: 456,
        likes: 34,
        comments: 22,
        status: "published",
        slug: "victoria-local-torneo-regional",
        excerpt: "Un partido lleno de emociones que terminó con victoria para el equipo de casa.",
        readTime: 3,
        source: "Corresponsal Deportivo",
        location: "Estadio Municipal",
        priority: 3,
        content: "Relato completo del partido con análisis de las jugadas más importantes.",
        summary: "Victoria 2-1 en el torneo regional",
        youtubeLink: "",
    },
]
