import type { Publicidad } from "@/lib/validations"

export const staticAds: Publicidad[] = [
  {
    id: "static-eldorado",
    title: "Eldorado",
    description: "Municipalidad de Eldorado",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://eldorado.gob.ar/",
    linkUrl: "https://eldorado.gob.ar/",
    imageUrl: "/placeholder.svg?height=300&width=600&text=Eldorado",
    images: ["/placeholder.svg?height=300&width=600&text=Eldorado"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-hyg",
    title: "hyg muebles",
    description: "Muebleria HyG",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.instagram.com/muebleriahyg6?igsh=MTJkd2Fsdnpxemc1cw==",
    linkUrl: "https://www.instagram.com/muebleriahyg6?igsh=MTJkd2Fsdnpxemc1cw==",
    imageUrl: "/placeholder.svg?height=200&width=300&text=HyG+Muebles",
    images: ["/placeholder.svg?height=200&width=300&text=HyG+Muebles"],
    isActive: true,
    createdAt: new Date("2025-11-06").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-gm",
    title: "gm",
    description: "GM Ingenieria y Servicios",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.instagram.com/gmingenieriayservicios/?igsh=MXhybGlyMGZhZGoyaQ%3D%3D#",
    linkUrl: "https://www.instagram.com/gmingenieriayservicios/?igsh=MXhybGlyMGZhZGoyaQ%3D%3D#",
    imageUrl: "/placeholder.svg?height=200&width=300&text=GM",
    images: ["/placeholder.svg?height=200&width=300&text=GM"],
    isActive: true,
    createdAt: new Date("2025-10-23").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-ucami",
    title: "Ucami",
    description: "Universidad Católica de las Misiones",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://www.ucami.edu.ar/ingreso.php",
    linkUrl: "https://www.ucami.edu.ar/ingreso.php",
    imageUrl: "/placeholder.svg?height=300&width=600&text=UCAMI",
    images: ["/placeholder.svg?height=300&width=600&text=UCAMI"],
    isActive: true,
    createdAt: new Date("2025-12-19").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-agua-dem",
    title: "Agua de las misiones dem",
    description: "Agua de las Misiones",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=Agua+Misiones",
    images: ["/placeholder.svg?height=200&width=300&text=Agua+Misiones"],
    isActive: true,
    createdAt: new Date("2025-06-06").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-imi",
    title: "imi imagenes",
    description: "IMI Imágenes",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://imiimagenes.com.ar/",
    linkUrl: "https://imiimagenes.com.ar/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=IMI",
    images: ["/placeholder.svg?height=200&width=300&text=IMI"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-imag",
    title: "imag",
    description: "IMAG Misiones",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://www.instagram.com/imag.misiones/?hl=es",
    linkUrl: "https://www.instagram.com/imag.misiones/?hl=es",
    imageUrl: "/placeholder.svg?height=300&width=600&text=IMAG",
    images: ["/placeholder.svg?height=300&width=600&text=IMAG"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-aries",
    title: "Aries",
    description: "Aries Minimarket",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.instagram.com/ariesminimarket/",
    linkUrl: "https://www.instagram.com/ariesminimarket/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=Aries",
    images: ["/placeholder.svg?height=200&width=300&text=Aries"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-estudio-juridico",
    title: "estudio juridico",
    description: "Estudio Jurídico",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Estudio+Juridico",
    images: ["/placeholder.svg?height=250&width=500&text=Estudio+Juridico"],
    isActive: true,
    createdAt: new Date("2025-10-16").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-gauler",
    title: "Gauler",
    description: "Gauler",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.instagram.com/eldopolis/p/C6gqfRuAa_x/",
    linkUrl: "https://www.instagram.com/eldopolis/p/C6gqfRuAa_x/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=Gauler",
    images: ["/placeholder.svg?height=200&width=300&text=Gauler"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-eldopolis7",
    title: "eldolpolis7",
    description: "Eldopolis 7",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Eldopolis+7",
    images: ["/placeholder.svg?height=250&width=500&text=Eldopolis+7"],
    isActive: true,
    createdAt: new Date("2025-02-11").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-misiotech",
    title: "misiotech",
    description: "Misiotech",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://misiotech.com.ar/",
    linkUrl: "https://misiotech.com.ar/",
    imageUrl: "/placeholder.svg?height=300&width=600&text=Misiotech",
    images: ["/placeholder.svg?height=300&width=600&text=Misiotech"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-eldopolis1",
    title: "eldopolis1",
    description: "Eldopolis 1",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Eldopolis+1",
    images: ["/placeholder.svg?height=250&width=500&text=Eldopolis+1"],
    isActive: true,
    createdAt: new Date("2025-02-11").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-eldopolis3",
    title: "eldopolis3",
    description: "Eldopolis 3",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Eldopolis+3",
    images: ["/placeholder.svg?height=250&width=500&text=Eldopolis+3"],
    isActive: true,
    createdAt: new Date("2025-02-11").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-eldopolis5",
    title: "eldopolis5",
    description: "Eldopolis 5",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Eldopolis+5",
    images: ["/placeholder.svg?height=250&width=500&text=Eldopolis+5"],
    isActive: true,
    createdAt: new Date("2025-02-11").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-estudio-juridicos",
    title: "estudio juridicos",
    description: "Estudio Juridicos",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=Estudio+Juridicos",
    images: ["/placeholder.svg?height=200&width=300&text=Estudio+Juridicos"],
    isActive: true,
    createdAt: new Date("2025-10-16").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-michelin",
    title: "Michelin",
    description: "Michelin",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Michelin",
    images: ["/placeholder.svg?height=250&width=500&text=Michelin"],
    isActive: true,
    createdAt: new Date("2025-10-08").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-municipalidad-puerto-piray",
    title: "municipalidadpuertopiray",
    description: "Municipalidad Puerto Piray",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://www.instagram.com/municipalidadpuertopiray/?hl=es-la",
    linkUrl: "https://www.instagram.com/municipalidadpuertopiray/?hl=es-la",
    imageUrl: "/placeholder.svg?height=300&width=600&text=Muni+Piray",
    images: ["/placeholder.svg?height=300&width=600&text=Muni+Piray"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-agua-misiones",
    title: "agua de las misiones",
    description: "Agua de las Misiones",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://aguadelasmisiones.com.ar/",
    linkUrl: "https://aguadelasmisiones.com.ar/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Agua+Misiones",
    images: ["/placeholder.svg?height=250&width=500&text=Agua+Misiones"],
    isActive: true,
    createdAt: new Date("2025-05-15").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-directv",
    title: "directv",
    description: "DirecTV",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://web.facebook.com/profile.php?id=61586485527172&sk=about&locale=es_LA",
    linkUrl: "https://web.facebook.com/profile.php?id=61586485527172&sk=about&locale=es_LA",
    imageUrl: "/placeholder.svg?height=200&width=300&text=DirecTV",
    images: ["/placeholder.svg?height=200&width=300&text=DirecTV"],
    isActive: true,
    createdAt: new Date("2026-01-22").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-cedap",
    title: "Cedap",
    description: "CEDAP",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.instagram.com/cedap.eldorado/",
    linkUrl: "https://www.instagram.com/cedap.eldorado/",
    imageUrl: "/placeholder.svg?height=200&width=300&text=CEDAP",
    images: ["/placeholder.svg?height=200&width=300&text=CEDAP"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-soita",
    title: "EL SOITA CARNE DE BÚFALO",
    description: "El Soita Carne de Búfalo",
    category: "Pequeña Principal",
    position: "Pequeña Principal",
    link: "https://www.eldopolis.com",
    linkUrl: "https://www.eldopolis.com",
    imageUrl: "/placeholder.svg?height=200&width=300&text=El+Soita",
    images: ["/placeholder.svg?height=200&width=300&text=El+Soita"],
    isActive: true,
    createdAt: new Date("2025-02-22").toISOString(),
    priority: 5,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-eldopolis2",
    title: "eldopolis2",
    description: "Eldopolis 2",
    category: "Mediana Principal",
    position: "Mediana Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=250&width=500&text=Eldopolis+2",
    images: ["/placeholder.svg?height=250&width=500&text=Eldopolis+2"],
    isActive: true,
    createdAt: new Date("2025-02-11").toISOString(),
    priority: 8,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
  {
    id: "static-montecarlos",
    title: "Montecarlos",
    description: "Montecarlos",
    category: "Grande Principal",
    position: "Grande Principal",
    link: "https://eldopolis.com/",
    linkUrl: "https://eldopolis.com/",
    imageUrl: "/placeholder.svg?height=300&width=600&text=Montecarlos",
    images: ["/placeholder.svg?height=300&width=600&text=Montecarlos"],
    isActive: true,
    createdAt: new Date("2025-02-10").toISOString(),
    priority: 10,
    clicks: 0,
    impressions: 0,
    targetAudience: [],
    budget: 0,
    costPerClick: 0,
  },
]
