import { z } from "zod"

export const NewsSchema = z.object({
    id: z.string(),
    title: z.string(),
    subtitle: z.string().optional(),
    description: z.string().optional(),
    mainCategory: z.string(),
    subCategory: z.string().optional(),
    tags: z.array(z.string()).default([]),
    author: z.string().optional(),
    date: z.string(),
    timestamp: z.string(),
    image: z.union([z.string(), z.array(z.string())]).optional(),
    imageUrl: z.string().optional(),
    imageCaption: z.string().optional(),
    featured: z.boolean().default(false),
    featuredType: z.string().optional(),
    breaking: z.boolean().default(false),
    views: z.number().default(0),
    likes: z.number().default(0),
    comments: z.number().default(0),
    status: z.enum(["published", "draft", "retired"]).default("published"),
    slug: z.string().optional(),
    excerpt: z.string().optional(),
    readTime: z.number().default(0),
    source: z.string().optional(),
    location: z.string().optional(),
    priority: z.number().default(0),
    content: z.string().optional(),
    video: z.string().optional(),
    audio: z.string().optional(),
    summary: z.string().optional(),
    youtubeLink: z.string().optional(),
})

export const PublicidadSchema = z.object({
    id: z.string(),
    title: z.string().optional().default(""),
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    images: z.array(z.string()).optional().default([]),
    linkUrl: z.string().optional(),
    link: z.string().optional(),
    position: z.string().optional().default("sidebar"),
    category: z.string().optional(),
    isActive: z.boolean().optional().default(true),
    startDate: z.string().optional(),
    endDate: z.string().optional(),
    priority: z.number().optional().default(0),
    clicks: z.number().optional().default(0),
    impressions: z.number().optional().default(0),
    targetAudience: z.array(z.string()).optional().default([]),
    budget: z.number().optional().default(0),
    costPerClick: z.number().optional().default(0),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
})

export type News = z.infer<typeof NewsSchema>
export type Publicidad = z.infer<typeof PublicidadSchema>
